### ISSUE TITLE
Remove search_srdb?

### ISSUE THREAD

**Issue by bpbond** [PNNL-SERC-COMPASS/COMPASS-synthesis#11]
Hey @stephpenn1 about the initial setup work you did with the `search_srdb()` function—I see where you were going and like it. Great initial commenting, log messaging, use of `grepl`. You were pursuing a solid strategy and taking a really robust programming approach. So 👏 

However, all that said...do you think we'll still need it, given how the code has developed subsequently? I'm not sure, but if not, it would be good to remove that 'dead code' from the Rmd.

**Comment by stephpenn1** [comment]
Yes now that we have a simpler filtering code we don't need that function, I will remove. Thanks though!
