### ISSUE TITLE
SP weeks of December 21 and 28 and January 4

### ISSUE THREAD

**Issue by bpbond** [PNNL-SERC-COMPASS/COMPASS-synthesis#2]
- [x] Please commit and push your code from [last week](https://github.com/PNNL-SERC-COMPASS/COMPASS-synthesis/issues/1)

Let's continue previous exploratory work at a deeper level.

- [x] How many observations (rows) are there for each category of the "Irrigated" manipulations? (Forests, grasslands, and agriculture only.) What categories exist?
- [x] What about for soil drainage? This should be simpler, with mostly "dry" and "wet"
- [x] What measurement variables are most common? I assume `Rs_annual` will be frequent but we're also interested in "Rh_annual" and "Rs_growingseason" in particular; maybe one of the Q10s too
- [ ] Try computing the _response ratio_ for each study in the Dry/Wet category, as `log(Rwet / Rdry)`. Graph these, with the RR on the X axis and study on the Y. For example like this (but for now without error bars):

![g20041](https://user-images.githubusercontent.com/1956468/102788046-0ab58b00-4370-11eb-9a50-7e05cba778d1.jpg)

Please don't hesitate to ping me if something is unclear! Thank you.

**Comment by bpbond** [comment]
By next Monday the 11th you and I should have both read the [Liu et al. paper](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.13156).

**Comment by bpbond** [comment]
BBL to do: literature search for relevant 2018-2020 publications that we can add to the analysis.

**Comment by stephpenn1** [comment]
@bpbond I used the `forcats` package to reorder right in ggplot (can probably do this in the pipeline if we want this ordering to be more permanent. I noticed some studies still have multiple response ratios... are there other variables im not capturing that could be causing multiple ratios?

![image](https://user-images.githubusercontent.com/20341158/103930175-585e2180-50ec-11eb-8a5a-fcbfa764fc30.png)

**Comment by bpbond** [comment]
😍 😍 😍 

Woo @stephpenn1 that looks _great_. Nice job!

The multiple RRs within a line are because there might be an irrigation +50%, irrigation +75%, etc. for a single year. They're each divided by the "None" Rs and produce separate dots.

**Comment by bpbond** [comment]
Suggestion: just have study author name on the y axis? (Not year.)

**Comment by bpbond** [comment]
Also ideally the y axis is "Smith 2010" where 2010 is the publication year, not the observation year.

**Comment by stephpenn1** [comment]
?? Would you like me to average multiple irrigation levels together or keep them as separate points?

![image](https://user-images.githubusercontent.com/20341158/103933469-6cf0e880-50f1-11eb-9922-11ee53708e8c.png)

**Comment by bpbond** [comment]
I would keep as separate points. Eventually we'll want to color the points by irrigation/drought level I think.

**Comment by bpbond** [comment]
Included your lovely graph in my slides for DOE!
