### ISSUE TITLE
Another synthesis example

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-SERC-COMPASS/COMPASS-synthesis#22]
Came across this and looked relevant, have you seen this @bpbond ?
-  Du et al. 2020, The response of soil respiration to precipitation change is asymmetric and differs between grasslands and forests https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15270

**Comment by bpbond** [comment]
Thanks @stephpenn1 — I did see that when it was published and had forgotten about it. Honestly I have some serious concerns about their methodology. Thanks for remind me about it; I've added to the Paperpile folder I've started for this work.
