### ISSUE TITLE
SP week of January 11

### ISSUE THREAD

**Issue by bpbond** [PNNL-SERC-COMPASS/COMPASS-synthesis#4]
Again please keep GitHub up-to-date with code, both here and in Js-Rs.

- [x] As in #2 , please make preliminary RR plots for (i) drought manipulations and (ii) wet-versus-dry using existing WRDB data
- [x] We would like to start to search recent literature for relevant papers not yet in SRDB. The latter goes through 2017 I believe. Please use Web of Science and/or Google Scholar to look for 2018-2020 papers related to soil respiration, drought, irrigation, etc. Keep a record of search terms used. Does this make sense?
- [ ] Read [Liu et al.](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.13156)

**Comment by bpbond** [comment]
https://www.sciencedirect.com/science/article/pii/S0038071716307738

**Comment by bpbond** [comment]
Could you provide an update @stephpenn1 ? That will help me create an issue for us for this coming week.

**Comment by stephpenn1** [comment]
Hi, response ratios are completed and I will complete the PR once issues are resolved. I started a document to keep track of recent papers [here](https://docs.google.com/spreadsheets/d/1n98yh99GqvutF4h8O1LzC8vYTfwezK9Dp4JIqXugRk0/edit?usp=sharing). This week I plan to start researching and fill that out.

**Comment by bpbond** [comment]
So would it be useful to have a new, expanded issue? It would for me, just to organize my thoughts, but at the same time don't want to disrupt your workflow.

**Comment by bpbond** [comment]
Oh just seeing #6
