### ISSUE TITLE
SP week of January 18 and 25

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-SERC-COMPASS/COMPASS-synthesis#6]
- [ ] look for 2018-2020 papers related to soil respiration, drought, irrigation, etc. Keep a record of search terms used. Summarize findings [here](https://docs.google.com/spreadsheets/d/1n98yh99GqvutF4h8O1LzC8vYTfwezK9Dp4JIqXugRk0/edit?usp=sharing)
- [ ] Read Liu et al. (link below). **Don't struggle through all of it.** Focus on the introduction and methods ONLY for now
- [ ] Install the [metafor](https://metafor-project.org/doku.php) R package and start playing with it: read through any vignettes, run examples

**Comment by stephpenn1** [comment]
@bpbond feel free to add

**Comment by bpbond** [comment]
Following up on #4 and Slack discussion w/ @stephpenn1 ...

The SRDB doesn't have everything we're going to need for this analysis. In particular, the following information isn't in it:
* Standard deviation of Rs and/or Rh (actually SRDB does have SD of Rs but we'll need to double-check this)
* Sample size (N)
* Treatment level in a quantitative form: e.g. fraction of control, so control would be "1" and a 50% increase "1.5"

These are all necessary for a formal statistical meta-analysis, letting us generate e.g. plot error bars.

How do we get this information? Options:
* Create a separate table that is merged with our SRDB data in the script.
* Start with the (Liu et al.](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.13156) dataset (see the Excel workbook that's part of the Supplementary Information), and build onto that, using the SRDB only as a cross-reference.

**Comment by bpbond** [comment]
...I'm inclined to keep our analysis a totally distinct dataset from that of Liu et al., but welcome your thoughts on this!

**Comment by bpbond** [comment]
Hi @stephpenn1 so one thing we could do pretty quickly is set up Shoshi with a google sheet that contains SRDB study numbers basically—it would be more or less the information you're using for the RR graph and she would add extra columns. What do you think?

**Comment by stephpenn1** [comment]
Yes that sounds nice and simple
